spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/bee-sso?autoCommit=false&useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&zeroDateTimeBehavior=convertToNull&serverTimezone=CTT
    username: root
    password: 123456

mybatis-plus:
  type-aliases-package: com.tookbra.bee.sso.uac.domain
  mapper-locations: classpath*:mapper/xml/**/*Mapper.xml